### ISSUE TITLE
Enhance account visibility management - authorization per account and per website

### ISSUE THREAD

**Issue by Tbaut** [polkadot-js/extension#1037]
It has been proposed in different ways in the past, and there has been a [grant](https://github.com/w3f/Grants-Program/blob/master/rfps/privacy-enhancement-polkadot-extension.md) for it. I'd like to tackle this in a PR, but first, I'd like to get your soft approval of the general idea and flow I'm thinking of.

#### Problem:
The eye open/close button per account works for all websites. If users want to show only account A on website A, and account B on website B, they'd have to go to the extension, make sure only account A is visible when they browse website A, or show only account B when they browse on website B. This is impracticable, and leads to the fact that users have most of their accounts visible for all website, which is a privacy threat.

#### Proposed solution:
Instead of having a mapping `website - authorization` and then `account - visibility`. I propose to have `website - authorization - account`. In practice the flow would be as follow:
- When connecting to a new website, users are prompted not only to give the authorization for this website to see their accounts, but also let them select which accounts are visible for this website
- Enhance the website management page to show how many accounts are connected, and on click which ones.
- Changing the current behavior of the eye open/close on the account overview to reflect the state for the currently visited website, and allow to change it with a single click. So as not to confuse users, and clearly show the new behavior, I would go for a different icon than the eye. Probably something like a link and broken link.
- As for the migration, I'd have to research a bit more the practicality, but if possible, I would start from scratch, and request new access for any website.

What do you think?

**Comment by Tbaut** [comment]
Thanks for your input. I'm definitely for something very much different than what the grant suggests :)

I think we should have a quicker way to make an account visible to a website than having to go to website management, but this is something we can see by actually using it, or we can create shortcuts by showing the current website at the top of the list for instance.

Sounds good for your suggestions having a quick button to select all is certainly handy for some use cases.

**Comment by jacogr** [comment]
We can certainly enhance from v1 - so would suggest getting the basics in-place and then make it "quick".

**Comment by jonasW3F** [comment]
Thanks for the discussion and the motivation to make this happen. The RFP was stating the problem and offered some initial ideas as solution, but I am certainly open to other and more lean approaches, especially from people that know the code. As long as this offers better account handling and improves the privacy of users in the end.

With regard to this:

> Changing the current behavior of the eye open/close on the account overview to reflect the state of the currently visited website, and allow to change it with a single click. So as not to confuse users, and clearly show the new behavior, I would go for a different icon than the eye. Probably something like a link and broken link.

How does the extension handle multiple tabs? Is it possible to switch the states of the account visibility based on the active tab? If it does, then the above-mentioned idea certainly makes sense. However, it is rather a "patchwork" approach, as the user would have exposed their accounts already in the first place.

So, I think there should be some solution to avoid the visibility of accounts at the first connection. I understand that assigning sites on initial connection to "groups" (i.e., low security, high security or whatever the user created) is cumbersome, because it would require a process to create and maintain those groups in the first place. 

To avoid this, we could indeed offer some pre-defined groups (show all (except hidden ones), show none (is that actually possible or equivalent to denying the website?) and lastly the more tedious but most granular solution of manually assigning each address that may be visible. This avoids creating user-defined groups.

With regard to migration, I am inclined to, at least, strongly propose to request new access to all sites, just so that this feature does not get lost and people are somewhat nudged to think about their privacy. We could still have a button in the welcoming screen (that explains the changes) that says "Leave everything as it is" (which basically exposes all addresses to previously connected sites). 

I hope this makes sense and as stated before, you are the experts that know whats possible and whats too complicated / cluncky.

**Comment by Tbaut** [comment]
> However, it is rather a "patchwork" approach, as the user would have exposed their accounts already in the first place.

There's a little misunderstanding. My solution is to default to not showing anything to any website by default. And Jaco's suggestion is to keep the account general visibility on top of this. Here's an example:
- Account A visible (open eye)
- Account B visible (open eye)
- Account X not visible (crossed eye)

When you connect to a new website, with your accounts as above, then you will only be able to select one or both Account A and Account B to share with this website. The Account X will not even be displayed to be selected, because it has been set as non visible.

> So, I think there should be some solution to avoid the visibility of accounts at the first connection

This is what I suggest, and was agreed. Per default no account is selected, no data is shared. Unless users select one, some or all accounts **and validate**, then nothing will be shared.

> To avoid this, we could indeed offer some pre-defined groups

Rather than talking about groups, I prefer to talk about a list of accounts (only the visible ones, with the eye open), and a "select all" button. I don't really see the notion of group being needed. As a user, unless it's on apps, I find myself actually needing only 1 or 2 account per dapp website.

Let me know what you think

**Comment by jonasW3F** [comment]
Thanks for clarifying, this makes sense to me now.

**Comment by Noc2** [comment]
It seems like we have now three teams/people interested in working on this project (@nodi-andy, see https://github.com/w3f/Grants-Program/pull/870, @web3cryptowallet, see https://github.com/w3f/Grants-Program/pull/879 and @[Tbaut](https://github.com/Tbaut)) and in my opinion it doesn’t make any sense, that three teams implement the same tools at the same time. 

So my suggestion is that we are going to make a decision in **two weeks** on which grant we are going to support. That said, I think there is a lot of work that needs to be done and we would be more than happy to support other UI/UX related projects. In general, we have a huge interest in supporting these kinds of projects. This also doesn’t necessarily be improvements/fixes to polkadot-js, you could also support other projects, like for example https://github.com/Nick-1979/polkadot-Js-Plus-extension or develop your own project. Therefore, I hope we can work together with all of you independently of this specific project.

**Comment by takahser** [comment]
FYI - we're a bit behind schedule here. We're still discussing, but we will be back with an answer on which grant to support very soon. Sorry for the delay and thanks for your patience! 🙌
