### ISSUE TITLE
Bring back message signing support for QR based account

### ISSUE THREAD

**Issue by Tbaut** [polkadot-js/extension#1070]
Background, please correct me if I'm wrong:
1. Raw byte signing was originally not supported for security reasons, we did not want users to be able to sign extrinsics while thinking they would only sign a message
1. A workaround to this was to wrap any message with `<Bytes></Bytes>`.
1. Signer only supports scale based decoding cf https://github.com/paritytech/parity-signer/issues/1014#issuecomment-1109718889
1. QR support was dropped in the extension as a result of ^ https://github.com/polkadot-js/extension/pull/1053/files

Being able to sign messages is greatly needed, we've seen this with parachain teams and crowdloans when users are requested to sign T&Cs or Dapp like Polkassembly requiring message signing to login with a web3 account.

I'm happy to be the one working on this and bring it back the right way in the extension, if there is a right way. As of now, my I'm lacking proper understanding of the situation to propose a meaningful solution. Opening this issue to discuss what should be the best approach.

**Comment by jacogr** [comment]
Yes, it was working - in Stylo.

However, Parity Signer apparently (now that support is in), decided to accept another incompatible payload, where it is means to be in SCALE. 

So basically, it doesn't work. Well, since there is no way to show 2 different messages depending on consumer, I dropped it. 

Maybe one day there is consistency in the way it is handled and it can be brought back. It is quite obvious this was not tested in Parity Signer and now it manifests as a "bug" here. Life is too short.

**Comment by Slesarew** [comment]
As far as I can tell, the payload used to use "sign message" protocol that implies scale encoding. By just scale-encoding raw payload we can keep things working without introducing new issues. Alternative would be introduction of new uos payload type, I'm not sure there are any benefits to that path. Also scale adds message length to signed payload, which ensures no funny stuff is signed on top of payload; I know, there is `<bytes>` wrapping, but it clearly misfired in abovementioined bug - when first bracket was recognized as scale symbol.

**Comment by jacogr** [comment]
Let me say this explicitly - this is not a "bug".

We have 2 incompatible implementations.

So I'm always happy to change to different formats, but please, don't come with things that was working, then doesn't work on a new implementation and then call it a "bug". This is an incompatible implementation out in the wild now. So things maybe need to adapt, no doubt - but this is due to a new, untested implementation that read the spec differently.

**Comment by Slesarew** [comment]
One way or another, Signer was getting 2 different formats of "sign message" payload and treated them similarly.

 I understand that scale-encoding raw payload makes no sense in general; but we should then implement it as another format of uos message and make sure that this format still does not allow the payload to be misinterpreted, and I'm not sure I understand what benefits we will get from it apart from compatibility, while scale-encoding looks like quite natural simple and robust solution.

We need to get this fixed either way, this could not be fixed on Signer side alone (since implementations that require messages to be scale-encoded are existing in the wild as well, I'm not sure if Stylo supports both formats - if not then there *is* a bug). Let's decide which path to take and run it through infosec.

**Comment by ntn-x2** [comment]
I am not too deep into how things are supposed to work, but I also do not see the benefit of SCALE-encoding a payload which is supposed to be interpreted for what it is, i.e., a raw payload.

Do I understand correctly that the current limitation with the signer is that since both SCALE-encoded transactions and raw payloads can start with the `<` symbol it is hard for it to distinguish which way it is dealing with without introducing potential security vulnerabilities?

**Comment by Slesarew** [comment]
Actually, there is no sense to send "raw payload" as utf-formatted thing. Thus, why don't we indeed add another uos payload type (04 or 05, whichever is free) and not attempt to string-convert it at all. We can even let Signer demand `<bytes>` wrapping as magic word or something like that (and then not show it or show it differently from actual payload).

**Comment by ntn-x2** [comment]
I guess your point makes sense. It is not possible to UTF-8 encode generic extrinsics, as far as I know.

**Comment by ntn-x2** [comment]
I guess your point makes sense. It is not possible to UTF-8 encode extrinsics, as far as I know.

**Comment by Tbaut** [comment]
> Unless one of the two implementations reading QRs change and the presentation possibly changes, this is never going to work.

Stylo is the underdog, and still has a manual way of being updated, which makes cutting a breaking release easier to handle. I'm ok to implement the scale decoding if this is what we decide, as it does not support it as of yet.

**Comment by jacogr** [comment]
Another one to check is Polkawallet, I do remember they _used_ to have QR functionality (but this is even before the rewrite), but actually atm I cannot import an account, so I'm assuming it is not even compatible on first step anymore. Cannot recall other apps, but don't follow along as closely as I should. Either way, a check around their stuff would also be in order.

Are we adjusting the base libraries as well to cater for old and new with detection - the reason being that not all apps are going to be updated in one-go, which means that there is going to be a flood of support from developers for "my user's message doesn't verify". At least when this flood comes in, I can point to "update the libs".

Or is it meant to be broken for some and the ball is in the user's court? 

Either way, I'm expecting a long tail of incompatibility reports down the line. (I'm actually not up for updating the base libs to detect and check both, it already is enough of a pain of wrapped vs unwrapped and each of the "little" checks adds a maintenance burden)

**Comment by jacogr** [comment]
... additionally I would suggest a uos spec fork that makes the implementation details 100% clear. Throwing the baby over to this side of the fence wastes a lot of time (and gets my blood boiling), so I would at least expect implementers to not have grey areas.

**Comment by Slesarew** [comment]
https://github.com/paritytech/parity-signer/issues/1049

**Comment by Tbaut** [comment]
Let's move on reg. this @Slesarew, a new release of the extension was made effectively breaking any current integration that worked with Stylo at least, and we didn't settle on an alternative :|

**Comment by Tbaut** [comment]
Based on this https://github.com/paritytech/parity-signer/pull/1069#issuecomment-1163448262 can we move forward with the implementation in Signer and add it back to the extension?

**Comment by Slesarew** [comment]
Yes, now that we have green light from security we can do that.

Be sure to eventually mark weird UTF symbols like non-renderable and technical ones when you re-implement this on Stylo side though. I haven't found a good solution myself yet.

**Comment by jacogr** [comment]
Closed in https://github.com/polkadot-js/extension/pull/1155
