### ISSUE TITLE
The version of chrome extension is too old

### ISSUE THREAD

**Issue by Tore19** [polkadot-js/extension#1148]
The newest release is v0.44.6, but the version of chrome extension is still v0.44.1. It's too old. When will the newest release  be published to the stores?

**Comment by jacogr** [comment]
The short answer: When it is ready. There are still 3 PRs outstanding, and since the last publish it has undergone big auth changes. It still needs a lot of testing and review. 

We don’t rush the extension to the stores - it is not broken, and with the long store review process any updates are not taken lightly.

**Comment by Tore19** [comment]
Got it. Thanks for your quick reply and hope the new version of the extension to the stores will be released soon.
