### ISSUE TITLE
createType(ExtrinsicPayload):: Unable to determine type from {"info":5,"type":"ExtrinsicPayload"}

### ISSUE THREAD

**Issue by yuzhiyou1990** [polkadot-js/extension#119]
code:
import createType from "@polkadot/types/codec/createType";
....
createType("ExtrinsicPayload", request, {  version: request.version})

request:
![image](https://user-images.githubusercontent.com/3783037/62752278-680dac80-ba99-11e9-9ee2-bf62e84d8c19.png)

error:
![image](https://user-images.githubusercontent.com/3783037/62752317-955a5a80-ba99-11e9-9b6e-bc9b876f6209.png)

**Comment by jacogr** [comment]
Can you just adjust the import here and retry?

import { createType } from ‘@polkadot/types’

Assuming you are on an api version >0.90 it means the type definitions are not properly injected, the above should make sure that logic does take place

**Comment by yuzhiyou1990** [comment]
Errors can also occur using the following code.

import { createType } from ‘@polkadot/types’ 

![image](https://user-images.githubusercontent.com/3783037/62757714-d446db00-baae-11e9-8603-39d69aea1f69.png)

**Comment by jacogr** [comment]
Ok, that is a completely different issue - so what happens is basically the following -

- to check that the user does not have multiple incompatible versions of types, a global/window is set
- in the above case, the extension itself has a copy of the types as well (as the apps UI has)
- so between these 2 (which are seperate instances), the above error gets flagged since they share the window/global context

So for extensions, would really suggest just taking the payload it gets and passing it as-is up to the background, i.e. not to work with the api/types directly inside the page. (Not really as a work-around for the above, but rather from a separation of concerns perspective, i.e. you want to expose as little as possible to the in-page context.) This is a big reason why the `signPayload` comes in as a JSON-like object, with no types.

If it really needs to be done via `createType` for specific reasons in the page context, the the following work-around may work -

```js
// inject all defined types, i.e. get around the "not found errors"
import '@polkadot/types/injector';
// import createType directly, bypass the multi-versions detector
import createType from '@polkadot/types/codec/createType';

...
createType("ExtrinsicPayload", request, { version: request.version})
```

Not optimal, but should work. Don't have a solution for the above "2 different contexts, 1 window object" atm.

**Comment by jacogr** [comment]
Also change the assert to `warn` only in the base, so at the very least it won't be a show-stopped (i.e. code breaks exactly there), in the future.
