### ISSUE TITLE
allow to filter accounts by site, not only by network

### ISSUE THREAD

**Issue by brenzi** [polkadot-js/extension#1267]
[X] Feature request

If I expose this extension to a site, that site could potentially learn about all my wallet addresses (I have to trust the site that my data is only processed client side). This is a severe privacy risk

I'd like to select per account:
* what network(s) to use the account on
* what sites are allowed to see the account

talisman does the latter, but not the former. And - it's not open source (yet?), so it is no option for me to use it

**Comment by Tbaut** [comment]
I don't think you can have the account by network since the extension is not aware of the networks the dapp is connected to.

As for the which account per website, this feature is implement since https://github.com/polkadot-js/extension/pull/1068 but there has been no public release of the extension since then.

**Comment by TarikGul** [comment]
> what network(s) to use the account on

As for now this can't be implemented

> what sites are allowed to see the account

As mentioned above this is implemented in #1068 

Therefore closing this issue as resolved.
