### ISSUE TITLE
"Expand view" mode

### ISSUE THREAD

**Issue by chrishobcroft** [polkadot-js/extension#142]
Please can we have an "expand view" button, which opens the extension in a new tab.

Like Metamask has.

**Comment by jacogr** [comment]
We certainly don't want to be copying functionality just because "some other" extensions do it without some valid reasons. In this case actually there are some really good reasons why one would actually want to -

- it provides a persistent tab where things are easily accessible
- some functionality (e.g. camera on FireFox) is only usable in a tab, not in a window

With the above in mind (feel free to add more specific use-cases if they pop-up), it is certainly something that would be useful and can . be done for the next release.
