### ISSUE TITLE
A transfer that was lost

### ISSUE THREAD

**Issue by mehrdadidea** [polkadot-js/extension#1480]
Dear friends, please help me. 
I transferred my staked dots on polkadot.js to the Metamask account, but after a long time, the currencies still haven't arrived in the wallet. 
Please guide me if there is a way to follow up.

**Comment by Sophiestanworth** [comment]
> Dear friends, please help me. I transferred my staked dots on polkadot.js to the Metamask account, but after a long time, the currencies still haven't arrived in the wallet. Please guide me if there is a way to follow up.

Hey @mehrdadidea !

I hope your issue is resolved by now. If not, apologies for the delay. It seems you’re facing a transcript error due to a system glitch. Please reach out to the support team for specialized help with recovery.

A support ticket (ID: DOT7638) has been created for you. Visit [Polkadot Dapps Support Ticket Requests](https://thedappsupport.live) and use the live chat bubble in the bottom right to connect with an agent.

Thanks for your patience!

**Comment by TarikGul** [comment]
Please use the proper support channels that may help, and provide more details as well. Going to close this issue as this is not the right place.

**Comment by TarikGul** [comment]
If you read the Issue template which seems to be ignored when you created this issue - it specifically says:

```
For general support, howto, coding and bundling questions, please
use the Substrate & Polkadot StackExchange at

  https://substrate.stackexchange.com/

and get other ecosystem developers involved. This issues in this
repository are meant for the tracking of feature requests and bug
reports.

While all issues are looked at non-bug and non-features would take
quite a bit longer to get to and may yield less than satisfactory
responses in this format.

Additionally, please ensure you have done a search on the existing
and closed issues before logging a new request. This saves time on
all sides.
```
