### ISSUE TITLE
Sometimes injection objects are not available

### ISSUE THREAD

**Issue by yuzhiyou1990** [polkadot-js/extension#152]
I use @polkadot-js/extension-inject, but sometimes I have the following problems.

https://polkadot.js.org/apps/#/accounts
![image](https://user-images.githubusercontent.com/3783037/64932874-74451080-d874-11e9-9465-61090fb44890.png)

Because window.injectedWeb3 is empty when DAPP is used.
----------
Code injected by Extension
![image](https://user-images.githubusercontent.com/3783037/64932889-89ba3a80-d874-11e9-9b21-3e62c4a15c00.png)

You can use CustomEvent to notify @polkadot/extension-dapp win.injectedWeb3 that it has been injected

**Comment by jacogr** [comment]
The issue with events are that extensions may or may not be available in the user's environment - so you cannot fire and hope for a response. I have never seen this on the polkadot-js sample version and I believe it is due to this -

https://github.com/polkadot-js/extension/blob/master/packages/extension/manifest.json#L20

So with the above the extension _should_ run before anything else, hence not seeing that exact same issue. There is certainly a gap to improve the loading experience (i.e. run at document load), but it will need some tweak/playing on both the `-dapp` & `-inlect` sides. 

Not 100% sure what it would look like, potentially something along these lines -

https://github.com/polkadot-js/extension/pull/129#issue-311411490

i.e. the promise wait for the loaded event, hopes that everything is done at that point and then queries. (Will need some playing). If you have any explicit ideas on what works for your specific case, a PR would also be welcome. 

(Would love to make sure it works for all users and all extension developers in 100% of the cases)

**Comment by yuzhiyou1990** [comment]
I've used "run_at": "document_start" in manifest.json file.

**Comment by jacogr** [comment]
@yuzhiyou1990 Did the problem just "disappear"? I would still like to have a more robust solution - whatever that may be. (So as indicated, will actually play with load options and see (a) how to make it not work & (b) what can be done to solve it)
