### ISSUE TITLE
Camera access automatically requested for no reason

### ISSUE THREAD

**Issue by Swader** [polkadot-js/extension#167]
When using the extension to auth (only first auth - no longer happens during the session) into a polkadot-enabled site like claim.kusama.network, the extension defaults to asking for camera access without the user triggering any QR scanning functionality manually.

- Steps to reproduce: it always happens, as long as the extension is unlocked but not authenticated in the site.
- Browser in which this was tested: Brave beta, 0.70
- Example site: https://claim.kusama.network

What happens:

- camera access is requested

What should happen:

- camera access request should be exclusively manual

**Comment by jacogr** [comment]
It asks for camera access to allow the . scanning of QR codes, e.g. for Parity Signer -

- https://apps.apple.com/us/app/parity-signer/id1218174838
- https://play.google.com/store/apps/details?id=io.parity.signer

And option would be to explicitly enable the functionality via Options (instead of just promoting)
