### ISSUE TITLE
How to get prompted once you have rejected allowing the dApp?

### ISSUE THREAD

**Issue by FahdW** [polkadot-js/extension#289]
Currently if a user rejects allowing the dApp access, there is no way to manually reprompt this sort of behavior. It just falls to the wayside, how do you reprompt the user to be able to allow access. In case of accidental rejection

**Comment by jacogr** [comment]
There is a management screen for the permissions in the pipeline. Because of the lack of that the changes are not persisted, so any of the following triggers a reset and will ask for re-auth-

- exiting the browser
- switching the extension off/on (e.g. chrome://extensions)
- extension upgrade (when new version is release)

TL;DR Horrible workarounds, but something. Management is in the pipeline.

**Comment by FahdW** [comment]
Thanks for the update, you can close at your discretion. I wonder if there's a simpler function that we can use. Is the data stored in memory that denotes whether or not a rejection occurred? If we can expose that variable to a simple reset it would be a quicker workaround.

**Comment by jacogr** [comment]
Sure, via settings you can have a toggle to  push a message that says "clear auth cache". If it is something somebody is up for, PRs are welcome.

**Comment by jacogr** [comment]
Closing, #289 tracks the issue (linked through)
