### ISSUE TITLE
Can't import an account to Chrome extension 

### ISSUE THREAD

**Issue by erichpapai** [polkadot-js/extension#398]
I participated 2 days ago in DOT private sale and my tokens were credited to my polkadot account. After I dowloaded the chrome extension for Polkadot I'm not able to import my existing account with my 12 word phrases, I can only create a new account.
I get this message :

**One of more extensions has been detected in your browser, however no accounts has been injected.

Ensure that the extension has accounts, some accounts are visible globally and available for this chain and that you gave the application permission to access accounts from the extension to use them.**

How can I import or inject my existing account to my Polkadot chrome extension ?

**Comment by jacogr** [comment]
So when accounts are injected, it gets injected with the genesisHash. (Unless you made it "invisible"). So to give an example -

![image](https://user-images.githubusercontent.com/1424473/88780652-99402a80-d18b-11ea-8be8-203082b5b4f6.png)

The account there is only associated with Polkadot, so it will only appear when connected to Polkadot. So if I connect to Kusama it won't show. (Ignore the little visibility indicator there, this one will never show up, but if it did is will be based on the chain selected)

Likewise, the following will only be on Kusama -

![image](https://user-images.githubusercontent.com/1424473/88780880-ec19e200-d18b-11ea-91f5-dc96726d2be2.png)

So check the following -

![image](https://user-images.githubusercontent.com/1424473/88780925-fb992b00-d18b-11ea-9fe9-8383602ab4d3.png)

The first setting, when unchecked never injects. The second will only be made available on that specific chain.

**Comment by martinade** [comment]
I have also been trying to restore a polkadot/kusama account from Seed Phrase and password, which I have been able to do on https://polkadot.js.org/ but there is no functionality for this in the extension.  I have KSM on the restored account but can't connect it to the Polkadot google  extension. 

Any help would be highly appreciated.

Thanks

**Comment by jacogr** [comment]
![image](https://user-images.githubusercontent.com/1424473/88781878-3485cf80-d18d-11ea-8de4-f69d2c82d693.png)

The second option allow import via mnemonic. You can use a raw hex seed as well in there (despite what the documentation says - it is unlikely to be "formally added" since memonics are stronger in recovery, but it detects and allows hex seed import)

**Comment by erichpapai** [comment]
I cant find where can I check the Visible (always inject).... I'm of course connected to  Polkadot Live.

![Snímka obrazovky 2020-07-29 o 11 28 06](https://user-images.githubusercontent.com/46692289/88783321-e8d42580-d18e-11ea-820d-6e065528d697.png)
 
And in Polkadot Chrome extension I can only add new account. Can't import from seed.

![Snímka obrazovky 2020-07-29 o 11 23 07](https://user-images.githubusercontent.com/46692289/88783346-f1c4f700-d18e-11ea-863e-eaf879b8dbab.png)

**Comment by jacogr** [comment]
First add an account. Once done the above menu becomes visible. (If you have no use for the initial account, feel free to delete it once anything else is added). 

This is a conscious decision since it is expected that people will store their accounts in the extension (not elsewhere first) and the initial creation needs to be as simple as possible. (Yes, people do complain and this may change with more feedback to have an avalanche of options as a start)

**Comment by martinade** [comment]
Thanks so much for your reply. But..... Where did you get those options from?  I cant find them anywhere?

Thanks

**Comment by martinade** [comment]
Sorry, I will try the option you've just sent. 
And hopefully, that will do it!
Thanks

**Comment by erichpapai** [comment]
Great, thanks. It works.

**Comment by martinade** [comment]
Ditto! 

Thanks for all your help, time, and talent!!!! 

Best of luck!

**Comment by jacogr** [comment]
Happy you guys are sorted :)

**Comment by trinityXmontoya** [comment]
Hi!

Could you explain why creating the first account if we can just 'forget' it immediately is necessary? I believe previous versions allowed you to import the seed without needing to create an account first.

**Comment by jacogr** [comment]
1. Avalanche of options at the start adds confusion
2. Each line of code adds maintenance overhead

Start needs to be as simple as possible. It doesn't get simpler with a single-click, since like mentioned, it assumes that users use this only. YMMV.

I am locking this now, it may change, may not change, no need in re-commenting on old issues.
