### ISSUE TITLE
Recreate account using seed phrase

### ISSUE THREAD

**Issue by ThomasDunnam** [polkadot-js/extension#412]

**Comment by ThomasDunnam** [comment]
I can't seem to find a way to create my Polkadot account on the extension using the seed phrase.

**Comment by jacogr** [comment]
So if you mean "mnemonic", the extension only supports sr25519.

If you mean a hex seed, https://github.com/polkadot-js/extension#why-cant-i-import-an-account-with-a-hex-encoded-private-key However... there is a hidden feature, in the same mnemonic box you can input the hex and it will accept it. Because of the above and discouraging anything-but-mnemonic, it will probably stay hidden, but is supported.

You can obviously import any type via JSON, also ed25519 and sr21159.

**Comment by ThomasDunnam** [comment]
When I created the account I got this message. 
"Please write down your wallet’s mnemonic seed and keep it in a safe place.
Mnemonic seed is used to restore your wallet. Keep it carefully in case you lose your assets." Now I can't find a way to use this seed.

**Comment by jacogr** [comment]
So, it is the mnemonic seed. In the extension, you can import it by using this option (last on the screenshot) -

![image](https://user-images.githubusercontent.com/1424473/91214104-e96ec600-e712-11ea-9888-de8d617eb717.png)

**Comment by ThomasDunnam** [comment]
This (screen shot) is all that comes up when I hit the extension logo in Brave or Chrome (I loaded it in both). 

![image](https://user-images.githubusercontent.com/36521755/91220029-8f0d3f80-e6e9-11ea-887b-a9918cf96073.png)

**Comment by jacogr** [comment]
First add an account. The above menu only become available after you have at least one. (The "add seed" option will make it back on the first page in a future release, it seems like a request that comes up frequently.)

**Comment by ThomasDunnam** [comment]
Ok, I did that and it worked! I appreciate your help very much!

**Comment by jacogr** [comment]
Perfect.
