### ISSUE TITLE
Remeber Me -Polkadot Extension timing 

### ISSUE THREAD

**Issue by arunrajansharma** [polkadot-js/extension#487]
I would like to request the team to implement a prolonged 15 min remember e.g if I have made a transaction in a 15 min time window, then the extension will not ask me for the next 15 mins. The current setup is quite cumbersome, requiring me to put my password every 15 mins. Thanks

**Comment by siman** [comment]
+1. This is very needed for Subsocial

**Comment by jacogr** [comment]
Actually had it this way around in the initial implementation, but ran out of time since it needed to go due to API updates - so the idea was to keep the checkbox there (and checked) when you sign. So each time you prolong. when unchecked, it forgets.

(Initial is still opt-in). 

Overall like it and it doesn't detract from security, nor add any additional (mostly unneeded noise).

**Comment by siman** [comment]
Amazing news :) thank you for good feedback, @jacogr

**Comment by siman** [comment]
@Tbaut any other ideas how to improve UX of extension and do not see a tx confirmation modal every single time? People keep complaining about this confirmation modal. Nobody wants to see it so often. Me included

**Comment by Tbaut** [comment]
Just to be clear, this has nothing to do with the UX of this extension. The "People keep complaining" certainly about the UX of a web3 application, which is different, and I'm happy to discuss since I'm also impacted as a user. This issue is not the right place though.

Making the web3 account keeping insecure is certainly not the best way to reach a broader audience and make the Dapps' UX better. 

My [comment](https://github.com/polkadot-js/extension/issues/487#issuecomment-707756110) is a heads up. Prolonging the 15min has been accepted above by Jaco, and I will submit a PR soon. This will not get rid of the Popup since we still want user approval.

**Comment by subsocialdev** [comment]
> Making the web3 account keeping insecure is certainly not the best way to reach a broader audience and make the Dapps' UX better.

@Tbaut what good UX solutions to this problem have you seen?
