### ISSUE TITLE
How to check for authorization without triggering allow access pop-up?

### ISSUE THREAD

**Issue by sahilnanda1995** [polkadot-js/extension#547]
`await web3Enable('my cool dapp');`

Above call immediately triggers authorization pop-up to allow or reject access, is there a way I can check for authorization before triggering the pop-up?

**Comment by Tbaut** [comment]
Hi, this is not possible, because this would mean you would have a way to identify if users have the extension silently (without the user knowing) which is not great.

For this reason, it is advised to have a button to let users "connect with the extension" so that this popup is displayed when the user requests it. You can then remember this in memory of your Dapp.

**Comment by sahilnanda1995** [comment]
Thank you so much @Tbaut 

> You can then remember this in memory of your Dapp.

Got it.
Also, is there a time limit after which extension forgets/resets approval for the Dapp after the last authorization.

**Comment by jacogr** [comment]
No limit. 

Well, there is actually - currently the auth state is stored in the extension memory, so it gets reset when the user restarts the browser.

**Comment by sahilnanda1995** [comment]
> currently the auth state is stored in the extension memory, so it gets reset when the user restarts the browser.

Got it, Thanks @jacogr 

"remembering certain dapps for future" can this be a feature for the extension or will this also raise some security issues?

**Comment by jacogr** [comment]
There is an issue logged to persist and allow the user to manage the dapp auth state.

**Comment by Tbaut** [comment]
closing since it directly overlaps with  #85
