### ISSUE TITLE
Verify integrity of browser extension to prevent attacks by fake extensions

### ISSUE THREAD

**Issue by jonasW3F** [polkadot-js/extension#552]
At the time ledger was still operating through browser extensions, I remember that hackers injected their fake extensions into the app-store and stole people's crypto. Even recently ledger users are under [attack](https://cointelegraph.com/news/ledger-wallet-warns-of-fake-google-chrome-extension-stealing-crypto)  through the app store (however, since ledger deprecated all their extensions, it is somewhat different).

Since most users probably don't get the direct link here in the GitHub, this could be a future attack vector. Also, the official extension in the Firefox store currently has around 1500 users and I can imagine that those numbers can easily be manipulated. Thereby, some "more frequently downloaded" fake app could be featured in the search list. I don't know how those stores operate but as it [seems](https://threatpost.com/google-yanks-106-malicious-chrome-extensions/156731/) there are plenty of issues.

I wonder, whether there is a way to strengthen the security here. Is there a possibility to checksum a browser extension? If so, it would a great idea if the polkadot.js/apps would check user's extension and only communicate with those matching the footprint.

I don't have much experience with browser extensions, so I have no idea whether this is possible or viable.

**Comment by Tbaut** [comment]
If the attack you are mentioning is to have a fake extension in the browser app-stores, the funds can be stolen the moment a users type their mnemonic, or upload a JSON and type their password. This will not need to touch any Dapp to happen. So the suggestion doesn't really work.

> I don't know how those stores operate but as it seems there are plenty of issues.

This is indeed where the burden is. We need to work with the browsers' store to make sure no such fake app is available. We need to keep an eye out, and track down any fake extension.

What the extension does since the v0.35 (just released), is to redirect users when they land on a malicious Dapp.

**Comment by jonasW3F** [comment]
> If the attack you are mentioning is to have a fake extension in the browser app-stores, the funds can be stolen the moment a user type their mnemonic, or upload a JSON and type their password. This will not need to touch any Dapp to happen. So the suggestion doesn't really work.
> 
That is true of course, it cannot prevent the loss of coins in all cases. However, there might be still a significant number of cases where a user learns about the attack before the unbonding period elapsed. Thereby, the user knows that the funds can be accessed from a third-party and countermeasures could be undertaken. 

It depends of course on the amount of work to implement something like this. If it can be done without much effort, I think it would definitely be worth it. If it's super complicated and creates issues down the line, it might not be worth it.

**Comment by Tbaut** [comment]
Fair point, although the past governance decisions seem not to be in favour of such bailouts, we shouldn't rule these out.

I've searched a bit and couldn't find a native way to get a hash/fingerprint/id of the extension, directly from the webpage without asking the extension (because this could then be tempered with). I'll keep looking. If there is such a way, we'd need to publish an actual list of known extension id (@polkadot/phishing is probably a good candidate).

**Comment by jonasW3F** [comment]
> Fair point, although the past governance decisions seem not to be in favour of such bailouts, we shouldn't rule these out.
> 
It is not necessary about bailouts. The user could ask for help from the community and coordinate some effort to get his/her transaction faster into the first available block than the hacker. Another point I forgot to mention is that even if we can't prevent the loss for individual users, this would be a good way to be quickly notified of the attack, because we learn that people start connecting with fake extensions. 

> I've searched a bit and couldn't find a native way to get a hash/fingerprint/id of the extension, directly from the webpage without asking the extension (because this could then be tempered with). I'll keep looking. If there is such a way, we'd need to publish an list of known extension id (@polkadot/phishing is probably a good candidate).

Thanks for your effort! I just wanted to bring up this issue so that it stays in mind if someone comes across a potential way to implement this.

**Comment by Tbaut** [comment]
Closing since there's sadly nothing we can do in the near term.
