### ISSUE TITLE
Can't sign when using external account in extension

### ISSUE THREAD

**Issue by yangwao** [polkadot-js/extension#553]
I'm trying to sign data https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Fkusama-rpc.polkadot.io#/signing where I have loaded external account in extension, but I think I miss some sign button or it should show something that it's not possible, limited sort of.

![image](https://user-images.githubusercontent.com/5887929/100713899-4f738500-33b5-11eb-80f1-234bcc6ee986.png)

**Comment by jacogr** [comment]
This is not implemented. The actual QR interface to eg. the Parity Signer does not have a sign-data-only mode.

**Comment by Tbaut** [comment]
This seems to be supported by the protocol and documented already https://github.com/maciejhirsz/uos#substrate-payload but maybe not in Signer?

**Comment by jacogr** [comment]
So it has been discussed at before - this is not on a critical support path for the Signer. 

Having said that, it _may_ work since at the first release of uos it was implemented to cover all paths, but has never been verified, nor tested, nor has any subsequent changes been made with that in-mind.

**Comment by Tbaut** [comment]
FYI, I'm taking a deeper look at this right now since this seems to be very useful for parachains to be able to let users claim tokens.

- User locks some funds with a Kusama account for a parachain
- The parachain is launched, users can sign a message on the parachain UI to prove that they are the owner of said account and claim their funds on a new parachain account.

Another use case is signing up on Polkassembly. It's not possible right now with an external account.
I hacked something on the extension and looking into the changes needed for Stylo and Signer since it isn't implemented there either.

**Comment by Tbaut** [comment]
I made a PR: https://github.com/polkadot-js/extension/pull/718
