### ISSUE TITLE
No Such File or Directory polkadot-exec-lerna.cjs - Trouble Building Extension Locally

### ISSUE THREAD

**Issue by juicebyjustin** [polkadot-js/extension#582]
Hi. I appologize if this is not the correct place to ask this question and will happily post elsewhere if there is a better location.

I am trying to build the extension locally using the master branch. I'm running `npm install` and it fails with the error: `no such file or directory, chmod /.../node_modules/@polkadot/dev/scripts/polkadot-exec-lerna.cjs`

The file in the error message does not exist. I am not a master of `npm` but do know that `npm_install` should have installed the file.

I found the GitHub repo for `@polkadot/dev/*` ([polkadot-js/dev](https://github.com/polkadot-js/dev/tree/master/packages/dev/scripts)) and do not see the file that is in my error message. I imagine that if this file was in the repo I would not be getting this error message.

How do I get by this error?

`node: v15.4.0`

`npm: 7.0.15`

`npm install`

```
npm ERR! code ENOENT
npm ERR! syscall chmod
npm ERR! path /Users/user/Documents/GitHub/extension/node_modules/@polkadot/dev/scripts/polkadot-exec-lerna.cjs
npm ERR! errno -2
npm ERR! enoent ENOENT: no such file or directory, chmod '/Users/user/Documents/GitHub/extension/node_modules/@polkadot/dev/scripts/polkadot-exec-lerna.cjs'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 
```

**Comment by jacogr** [comment]
That is a bug in the dev repo, here - https://github.com/polkadot-js/dev/blob/master/packages/dev/package.json#L23

We have not used lerna for quite some time, but it seems that yarn doesn't complain. will get a fix in there. 

npm 7 should work since it supports workspaces, however it hasn't been tested at all. Actually the build scripts in dev explicitly refers to `yarn` in a number of places, so when for instance calling the build script in a repo that use `@polkadot/dev` (all of them), it will have some issues.. 

It has been on the list to see how the repos work with npm 7 & the new workspaces feature, seems we hit the first snag

**Comment by juicebyjustin** [comment]
Thanks @jacogr. 

On a side note, I'm trying to join the Element.io discussion and I get an error that says `Failed to join room
You are not invited to this room.`

I found the link to Element.io in the first paragraph [here](https://wiki.polkadot.network/docs/en/build-index).

**Comment by jacogr** [comment]
Not 100% sure, I juts looked and the actual room address (unless the one in the page is an alias), is the following -

`#polkadot-watercooler:web3.foundation` (so the server is not on matrix.org, I believe that may be an alias)

**Comment by juicebyjustin** [comment]
Gotcha. Where have you found to be the best placed for development centered discussion around Polkadot?

**Comment by jacogr** [comment]
`#substrate-technical:matrix.org`

**Comment by jacogr** [comment]
This was adjusted in the dev repo.
