### ISSUE TITLE
Lack of Westend network

### ISSUE THREAD

**Issue by TomaszWaszczyk** [polkadot-js/extension#601]
I do not see Westend network while trying to create new Westend address.

System: Ubuntu 20
Web browser: Firefox

![lackofwestend](https://user-images.githubusercontent.com/1605705/103140897-a5a1c280-46ec-11eb-9e33-02c64c8f6cc1.gif)

**Comment by jacogr** [comment]
The extension does not list any test networks. The reason is that they do not form part of the ss58 registry. 

Additionally testnets are quite unstable, so attaching via genesisHash is problematic since a rest would mean a discrepancy in what is published on the stores vs what is on-chain. (For instance in the case of Westend it is on version 3 at the moment)

**Comment by TomaszWaszczyk** [comment]
I see. Thanks for the info.
