### ISSUE TITLE
Ledger Nano X is not recognized

### ISSUE THREAD

**Issue by asiniscalchi** [polkadot-js/extension#682]
Hi all,
I have 2 Ledger devices:
- Nano S (USB-2) : all good: I can create Polkadot and Kusama account
- Nano X (USB-C): the device is not recognized <---- The Issue

![image](https://user-images.githubusercontent.com/2387339/111737613-39180900-8880-11eb-992c-07d18244dede.png)

Thanks

**Comment by jacogr** [comment]
Don't have a Nano X myself, but a couple of questions -

- Are you only using one at a time?
- no Ledger Lie or apps UI open? (WebUSB struggles attaching to multiples)

Since the one works, I'm assuming the second is not true. (But just confirming).

the above really sounds like a WebUSB issue. May I also just ask to see if the apps UI recognizes it (don't need to create the account there, just as a double-check - the two, e.g. extension and apps UI cannot be used at the same time, sadly that is an irritating limitation)

**Comment by asiniscalchi** [comment]
Yes, I am using it alone and with only the extension active to have the most "vanilla" environment. 
Just to add that webUSB recognize successfully the device: I can add an account directly by polkadot.js app.

**Comment by jakehemmerle** [comment]
I have the Nano X myself, and I've had no issues adding accounts via the extension.

**Comment by asiniscalchi** [comment]
Some more infos: 
this is whaat I get when I connect my Nano X without starting the Polkadot application on the ledger:
![image](https://user-images.githubusercontent.com/2387339/113662305-20915680-96a8-11eb-9ba3-6f24517ea01d.png)
then, when I start the Polkadot app no device is shown... same with Kusama

**Comment by asiniscalchi** [comment]
Ok I found it: it's the browser:
Brave: Version 1.22.70 Chromium: 89.0.4389.105 (Official Build) (64-bit) NOT WORKING
Chromium: Version 89.0.4389.114 (Official Build) snap (64-bit) NOT WORKING
Chrome: Version 89.0.4389.114 (Official Build) (64-bit) WORKING
