### ISSUE TITLE
Address format does not change in the extension

### ISSUE THREAD

**Issue by r0qs** [polkadot-js/extension#714]
Hi, 
I'm using ledger nano x with Polkadot extension v0.37.1 in a Chromium browser v90.0.4430.93. However, when I select a different `display address format` in the extension settings, it does not change the displayed address in the extension.

I imagine that this is not the intended behavior. How can I ensure that the address displayed by the web application that uses the Polkadot extension is the same but in a different format if the extension does not shows that?

**Comment by jacogr** [comment]
When you add a Ledger account, say with the Polkadot app - that is only valid on the Polkadot network. 

Do not try to use it on any other substrate network, it will fail, also don't use it as a recipient of funds, the apps is for Polkadot or if you have the Kusama app and add it, Kusama, etc.

Due to this, the address format does not change - it is linked to the network the apps is for.

**Comment by r0qs** [comment]
Oh, I see. Thanks for the clarification. Maybe it would be helpful to have a message saying that when importing the account using ledger? Because this can lead to users mistakenly using the wrong addresses.

**Comment by jacogr** [comment]
The network selection is the first thing you do when adding an account - it is only available on that network. This means the account is associated with a specific genesisHash (which the actual on-Ledger app also uses to sign transactions).

Any application that integrates with the extension should never show the accounts where the genesisHash doesn't match the chain it is connected to. If an app does that, the app is doing the wrong thing. This means that account should never be visible on any non-supported chains. 

Since everybody is human, even developers, issues do slip into code that does checks against which networks the account is usable on, but any application that doesn't filter on this network correctly should get it known and fixed.

**Comment by r0qs** [comment]
Closing since is not a problem with the extension :)
