### ISSUE TITLE
Extension doesnt show Moonbeam address format

### ISSUE THREAD

**Issue by joelamouche** [polkadot-js/extension#798]
While it was showing as an option in my local build, it doesnt show in the production app. How long does it take before a merged PR goes into production?

**Comment by jacogr** [comment]
Quite some time. It is a manual release with having to wait for store approvals (which generally takes between 2 - 14 days on average)

With that in mind manual releases are not done often - it is quite close, however we are still probably 2 odd weeks out before I will cut one. (There are some issues with the current feature set introduced since the last release)

**Comment by joelamouche** [comment]
ok goot to know. Please let us know when the next release is happening. Hopefully we can get the metamask in as well
