### ISSUE TITLE
New account process restart on focus lost

### ISSUE THREAD

**Issue by Tbaut** [polkadot-js/extension#81]
I have 2 problematic work-flows:

1) create new account
- Click create a new account
- Copy the seed given to me in clipboard to paste it in my password manager later on.
- I am asked for a password, I need my password manager
--> the extension looses focus and when getting back to it, clicking to create a new account displays a new seed

2) import account from mnemonic
- Click to import account
- Paste seed from the clipboard (copied from password manager before starting the process)
- Password is asked
--> I'm screwed because I can't click away from the extension to use my password manager otherwise it'll loose focus and start from scratch

Both of these problems can be worked around by using pen an paper to manually copy the mnemonic and keep the clipboard for the password.

Metamask is bypassing these problem by first asking for a password at first launch before anything and then using it to encrypt any account keypair. Creating a new account doesn't ask for a password.

**Comment by jacogr** [comment]
It should just be more clever is keeping the current state, i.e. you are busy generating an account, don't switch to the first page.

I don't have an issue with the master-password approach, but actually kept away from it for per-account control. (So each is encrypted with its own password, as opposed to having a global password that encrypts storage).

**Comment by jacogr** [comment]
Still an issue, but user can open in a tab so there is a workaround.

**Comment by infinity0** [comment]
@jacogr How do you open this in a new tab? Can this be mentioned in the UI, so that users can do this when they are hit by the bug? Not everyone knows to go through the github issues.

Also, the issue is *still an issue*, can it be re-opened please.

**Comment by jacogr** [comment]
![image](https://user-images.githubusercontent.com/1424473/79761556-e9ecef80-8321-11ea-8b62-f926f7614c0d.png)

Re-opening serves no purpose, since there is no work that will be done on this - there is a work-around and this is actually non-solvable otherwise, since the popup _will_ close, due to the way a browser works.

**Comment by infinity0** [comment]
It is not obvious in the "new account" UI that the workaround is to open the extension in a new tab, most users aren't smart enough to link these options together. What would be an improvement would be:

- try to detect if the extension is being run in a new tab, and if not tell the user to do so, or
- if detection is impossible, then clearly and directly communicate to the user that they should restart this funtcionality in a new tab, and give them a button to click right there and then to do it, rather than to have to click 3 times somewhere else
