### ISSUE TITLE
dot-js extension not working properly to send DOT out

### ISSUE THREAD

**Issue by DC-1116** [polkadot-js/extension#854]
I do not get any option to see my balance or send my DOT in  my CHROME extension. Any advice?

I can see my balance on Polka Scanner, but no way to send it out. Anyone with the same issue?

I have remove the extension and downloaded again. Same issue remains.

**Comment by jacogr** [comment]
It is by design. It does not connect to any networks by itself, retrieve balances or send transactions.

As per the README and the documentation at https://polkadot.js.org/extension/ - it only manages accounts. If you wish to send, check balances, interact with parachains, participate in voting use something like http://polkadot.js.org/apps/ which can interact with the accounts stored in the extension.

**Comment by Champ11jun1980** [comment]
Not able to download extension & use it
