### ISSUE TITLE
Polkadot js plus extension 

### ISSUE THREAD

**Issue by Nick-1979** [polkadot-js/extension#872]
Hello, I am working on the extension to upgrade it so that can be easily used by non technical users. Currently, view/refresh balance, transfer funds, view tx history and view as QR code are implemented. Easy staking is in progress. Any comments/contributions  are appreciated.
The link is: https://github.com/Nick-1979/polkadot-Js-Plus-extension

Ps: after completing can be requested as a pull request.

**Comment by jacogr** [comment]
The extension, by design, doesn't connect to the network, i.e. transfers/balances won't be implemented and is not in the goals of the project. There used to be teams that were doing "fully-featured" extensions, but not sure if they ever saw the light.

Good luck with the effort. It is certainly something that users are asking for in extensions, e.g. metamask-like capabilities.

**Comment by Noc2** [comment]
@Nick-1979  Sounds interesting. We had a few teams working on browser extensions in the past, see browser extensions [here](https://github.com/w3f/Grants-Program/blob/master/docs/polkadot_stack.md). But none of them are currently actively maintained. If you are interested in working on one, feel free to apply for a [grant](https://github.com/w3f/Grants-Program).
