### ISSUE TITLE
Passwords not working

### ISSUE THREAD

**Issue by michalisFr** [polkadot-js/extension#892]
Some users have reported their password not working even after restoring with the mnemonic phrase and setting it again.

While troubleshooting with a user setting a very simple password as test worked. As part of the troubleshooting process we asked the user to type the password in a doc and copy it from there both during creation and when decrypting, and it sill failed. 

The recommendation we have is to make sure their keyboard is set to English, use only letters and numbers and avoid using any special characters, like hyphenated letters. Symbols seem to work normally.

It's not clear what the problem is but this looks like some unicode issue perhaps, where users use characters from other alphabets or with hyphenation and the password is accepted upon creation but fails to decrypt afterwards.

**Comment by ltfschoen** [comment]
In my own personal experience, I always first create accounts using Polkadot.js Apps, and then I import it into the Polkadot.js Extension using the JSON file to check that I can at least restore it with the password in future before I transfer any funds into it.   On many occassions it hasn't worked, and on every occasion it was because I accidentally had caps lock turned on.

So perhaps a possible improvement (in addition to asking users to enter their password twice as confirmation) is to warn the user if the password they have entered only contains capital letters.
Or add to a troubleshooting guide for "forgot password" a reminder to try entering your password using all-caps before trying other means like brute force

**Comment by jacogr** [comment]
Without an explicit testcase, this will just languish since as logged you are asking to find "maybe" a needle in a haystack.

For reproducable samples, would suggest something like -

- create an account with password `foobar`
- try to send a transaction from this account, fails

So basically, on failures like these, you need to be 100% sure it is something in the handling (with a specific testcase for it), otherwise it could just boil down to human issues. An explicit failure would be great to have a reproducable case.

**Comment by michalisFr** [comment]
Thanks @jacogr. Yes, this makes perfect sense. And I tried a few passwords with special characters and different keyboard languages but was unable to reproduce. So, I'll go ahead and close this and if we encounter a reproducible case where it's clear there's something wrong with handling I will reopen.

**Comment by michalisFr** [comment]
Ok, I was able to reproduce _something_.

I set the password "ελικόπτερο" (this is Greek for helicopter). Here are the tests I made:

1. Write down the password on a doc and copy paste it both during account creation and making a tx. It works both times.
2. Set the password to _ελικοπτερο_ without the accent on o. I both typed it in directly and copy-pasted it when creating the account and when making a tx. It worked both times.
3. I manually typed _ελικόπτερο_ on account creation and when making a tx, and it worked both times.
4. But if I copy-paste _ελικόπτερο_ from a doc upon account creation and then try to type it in when making a tx, I get an error that it can't decode.

Typing the _ό_ requires two key strokes: ";" + "o". So perhaps it translates it to two distinct characters when typing a character like that, but a single character if you copy-paste it.

**Comment by michalisFr** [comment]
Yes, this seems to be the case.

In the following screenshot:
![Screenshot 2021-12-10 at 4 58 05 PM](https://user-images.githubusercontent.com/45905709/145594350-afd1a5ea-f442-418c-9ec5-e6411b426c79.png)

in the first field I typed in _ελικόπτερο_ and in the second I copy-pasted it, but it doesn't recognise them as the same password.

**Comment by michalisFr** [comment]
Not sure whether that's what these users stumbled upon or how likely this is to happen in real life (seems pretty edge case), but perhaps something to look into.
