### ISSUE TITLE
Ethereum accounts cannot be imported via QR

### ISSUE THREAD

**Issue by kianenigma** [polkadot-js/extension#974]
A QR code with this format e.g. `ethereum:{H160}@1:test_name` can be imported to the apps ui, but not the extension. 

Example: 
![qrcode (1)](https://user-images.githubusercontent.com/5588131/149469831-2d00116b-59c6-44f9-b90b-5e87374f36db.png)

Overall, it would be good if there were easy ways to import an ethereum address using only the H160 address (e.g. if it lives in Ledger, I think you can only export your H160 address and not the full pubkey), for display-only purposes, without the need to ever sign anything.

**Comment by jacogr** [comment]
All Ethereum support has been contributed, so PRs are welcome to extend _if_ the ecosystem wallets has some support for this  - this is not something I can test, since out of my wheelhouse and usage patterns.

The focus really is on supporting Kusama/Polkadot in the base libraries, anything over that would need contributions.
